server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chmald/az-spring-app-demo-config
          default-label: main
          clone-on-start: true
        # For local development, use native profile with file system
        native:
          search-locations: classpath:/config
  security:
    user:
      name: configuser
      password: configpass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: false
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.azure.demo: DEBUG
    org.springframework.cloud.config: DEBUG