apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  DB_URL_USER: "jdbc:postgresql://your-postgres-server.postgres.database.azure.com:5432/userdb"
  DB_URL_PRODUCT: "jdbc:postgresql://your-postgres-server.postgres.database.azure.com:5432/productdb"
  DB_URL_ORDER: "jdbc:postgresql://your-postgres-server.postgres.database.azure.com:5432/orderdb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: servicebus-config
data:
  AZURE_SERVICEBUS_NAMESPACE: "your-servicebus-namespace.servicebus.windows.net"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  AZURE_KEYVAULT_ENDPOINT: eW91ci1rZXl2YXVsdC52YXVsdC5henVyZS5uZXQ=  # your-keyvault.vault.azure.net
  APPLICATIONINSIGHTS_CONNECTION_STRING: SW5zdHJ1bWVudGF0aW9uS2V5PWV4YW1wbGUta2V5  # InstrumentationKey=example-key
  DB_USERNAME: YXp1cmVhZG1pbg==  # azureadmin
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  AZURE_SERVICEBUS_CONNECTION_STRING: RW5kcG9pbnQ9c2I6Ly95b3VyLXNlcnZpY2VidXM=  # Endpoint=sb://your-servicebus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.yml: |
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
    logging:
      level:
        com.azure.demo: INFO
        org.springframework.cloud: INFO